/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

// Apply a specific Java toolchain to ease working on different environments.

tasks.register("my-task") {
    doLast {
        println("This is my task")
    }
}
allprojects {
    repositories {
        mavenCentral()
    }
}
